### LIST ALL MESSAGES
GET  http://localhost:3000/messages/

### POST NEW MESSAGE
post http://localhost:3000/messages
content-type: application/json

{
  "content": "Hey there!!!🚀🚀🧨",
  "age": 12,
  "isAdmin": true
}

### GET ONE MESSAGE BY ID
get http://localhost:3000/messages/12